name: Smoke Test

on:
  workflow_call:
  workflow_dispatch:

permissions: read-all

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '24.3.0'
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Prepare dotenv
        env:
          CHAINLIT_ENV_CONTENT: ${{ secrets.CHAINLIT_ENV_CONTENT }}
        run: |
          set -euo pipefail
          if [ -n "${CHAINLIT_ENV_CONTENT:-}" ]; then
            printf '%s' "${CHAINLIT_ENV_CONTENT}" > .env
          else
            python3 scripts/start_local.py --non-interactive
          fi

      - name: Run smoke test
        run: python3 scripts/smoke_test.py
